version: "3.7"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
